- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: Installed
    loop:
    - gcc
    - mysql 
    - git
    - zip