- name: Filters
  hosts: local
  connection: local
  tasks:
    - name: Handle undefined variable
      ansible.builtin.debug:
        msg: "Hello {{ person | default('Ramesh') }}"

    - name: Convert string to list
      vars:
        fruits: "apple,banana,orange"
      ansible.builtin.debug:
        msg: "Fruits are: {{ fruits | split(',') }}"

    - name: convert map into list
      vars: 
        course:
          name: ansible
          duration: 120hrs
          trainer: siva
      ansible.builtin.debug:
        msg: "course info: {{ course | dict2items }}"
    - name: convert list into map
      vars:
       course:
        - {'key': 'name', 'value': 'ansible'}
        - {'key': 'duration', 'value': '120hrs'}
        - {'key': 'trainer', 'value': 'siva'}
      ansible.builtin.debug:
        msg: "Course info: {{ course | items2dict }}"